### ISSUE TITLE
Unable to view 'Dependency Analytics Report'

### ISSUE THREAD

**Issue by psiservices-stuartclark** [redhat-developer/intellij-dependency-analytics#122]
I get the below issue when trying to view the report. I have Maven installed via SDKman, and Intellij is pointing to my installed Maven rather than the bundled. MAVEN_HOME variable also resolves correctly.

_Can't run report generation [90m2:20PM[0m [1m[31mFTL[0m[0m Please make sure Maven is installed. Hint: Check same by executing: mvn --version [31merror=[0m[31m"exec: \"mvn\": executable file not found in $PATH"[0m_

**Comment by TomerFi** [comment]
Mac user?

**Comment by TomerFi** [comment]
Try running IntelliJ from as a Terminal app instead of a Gui one:
```
/Applications/IntelliJ\ IDEA.app/Contents/MacOS/idea
```

See [this](https://intellij-support.jetbrains.com/hc/en-us/community/posts/7401690420242-PATH-variable-is-different-in-IntelliJ-terminal-v-s-mac-terminal?page=1#community_comment_7401740236946).
