### ISSUE TITLE
Consider leveraging the OSS Review Toolkit's Analyzer

### ISSUE THREAD

**Issue by sschuberth** [redhat-developer/intellij-dependency-analytics#14]
I was just coming across this project, and was reading in the `README`:

> 'Dependency Analytics' plugin supports projects using Maven, projects build on npm (Node ecosystem) and projects using Python. Extending support for Golang and other languages is currently under progress.

As the founder of the OSS Review Toolkit (ORT) I was wondering whether it would make sense for you to consider leveraging ORT's Analyzer [which supports Golang and several more languages / dependency managers](https://github.com/oss-review-toolkit/ort#analyzer).

**Comment by jeffmaury** [comment]
This plugin is based on https://github.com/fabric8-analytics/fabric8-analytics-lsp-server so you should rather contact them there
