### ISSUE TITLE
LSP Error - Cannot start server

### ISSUE THREAD

**Issue by tlaak** [redhat-developer/intellij-dependency-analytics#21]
I'm getting the following error from the plugin: 

```
LSP Error - Can't start server, please check settings
Cannot run program "node" (in directory "/path/to/project"): error=2, No such file or directory
```

I have node in my path, but I'm using nvm instead of a system level node. It shows up as `/Users/myname/.config/nvm/12.19.0/bin` when I run `echo $PATH` in terminal.

I'm also using a fish shell, which might make things more complicated but the `echo $PATH` output also contains the nvm path to node binary when I run it under the default zsh shell.

How to fix the issue?

**Comment by TomerFi** [comment]
We no longer use node to run the LSP Server.
This can be closed.
