### ISSUE TITLE
Dependency Analytics plugin does not analyze opened files when launching IDE or opening a project

### ISSUE THREAD

**Issue by dvandra** [redhat-developer/intellij-dependency-analytics#3]
Hi @jeffmaury 

Dependency Analytics plugin version 0.0.2.9 is not working with Intellij IDEA 2019.3.2.

Can you help with this or any pin-points you suggest?

**Comment by jeffmaury** [comment]
Can you describe the problem you have. Please join the IDEA logs if possible

**Comment by dvandra** [comment]
Dependency Analytics Plugin with IDEA version 2019.2.4 is working but need to disable all other installed plugins for that.

IDEA version 2019.3.2 this plugin is not working.

I am not able to see any logs in IDEA, may be there is some LSP related issue or issue at very initial level.

Any suggestions?

**Comment by jeffmaury** [comment]
To get the logs, Help -> Show Log in explorer or Help -> Diagnostic Tools -> Show Log in Explorer and then you should have an idea.log to send

**Comment by jeffmaury** [comment]
Will check with 2019.3.2

**Comment by dvandra** [comment]
> To get the logs, Help -> Show Log in explorer or Help -> Diagnostic Tools -> Show Log in Explorer and then you should have an idea.log to send

I mean i can see the logs but nothing from Analytics plugin.

**Comment by dvandra** [comment]
Hi Jeff, I just checked for new early access version 2020.1 and Dependency Analytics Plugin is working for the new upcoming version!

For version 2019.2.4 it sometimes works and sometime doesn't work but after disabling Android support from plugin it works well!
